version: '3'

services:
  backend:
    build:
      context: .
    container_name: appl
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/profilefind
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=profilefind'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432